name: Feedback
description: File a bug report.
body:
  - type: dropdown
    id: mark
    attributes:
      label: Mark
      options:
        - Peugeot
        - Citroen
        - DS
        - Opel
        - Vauxhall
      default: 0
    validations:
      required: true
  - type: input
    id: model
    attributes:
      label: Model
      placeholder: ex. e208
    validations:
      required: true
  - type: dropdown
    id: year
    attributes:
      label: Year
      options:
        - 2025
        - 2024
        - 2023
        - 2022
        - 2021
        - 2020
        - 2019
        - 2018
        - 2017
        - 2016
      default: 0
    validations:
      required: true
  - type: dropdown
    id: engine
    attributes:
      label: Engine
      options:
        - Electric
        - Fuel
        - Hybrid
      default: 0
    validations:
      required: true
  - type: dropdown
    id: remote
    attributes:
      label: Remote service
      options:
        - No
        - E-remote
        - Connect Plus
      default: 0
    validations:
      required: true
  - type: input
    id: hass
    attributes:
      label: HomeAssistant version
      placeholder: ex. 2025.5.1
    validations:
      required: true
  - type: input
    id: release
    attributes:
      label: Integration version
      placeholder: ex. 2025.6.3
    validations:
      required: true
  - type: textarea
    id: request
    attributes:
      label: What happened?
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Enable the debug log of this integration from your configuration.yaml:
        ```
        logger:
            default: error
            logs:
                custom_components.stellantis_vehicles: debug
        ```
        before pasting here, please remove your personal data (access_token, refresh_token, customer_id, vin, vehicle_id, coordinates, etc).
  - type: textarea
    id: logs
    attributes:
      label: Log output
      description: Please copy and paste the log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
