name: Close inactive issues/PRs
on:
  workflow_dispatch:
  schedule:
    - cron: "30 1 * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v9
        with:
          days-before-issue-stale: 15
          days-before-issue-close: 5
          stale-issue-label: "stale"
          stale-issue-message: "This issue is stale because it has been open for 15 days with no activity."
          close-issue-message: "This issue was closed because it has been inactive for 5 days since being marked as stale."
          days-before-pr-stale: 15
          days-before-pr-close: 5
          stale-pr-label: "stale"
          stale-pr-message: "This PR is stale because it has been open for 15 days with no activity."
          close-pr-message: "This PR was closed because it has been inactive for 5 days since being marked as stale."
          repo-token: ${{ secrets.GITHUB_TOKEN }}
