name: Pre-Release

on:
  workflow_dispatch:

jobs:
  deploy:
    if: github.event.pull_request.merged || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all commits and tags

      - name: Get pre-release name
        id: pre-release-tag-name
        run: |
          # Fetch all tags
          git fetch --tags
          
          # Fetch last tag
          last_tag=$(git tag -l --sort=-creatordate | head -n 1)
          
          # Fetch last release
          last_release_tag=$(git tag -l '[0-9]*.[0-9]*.[0-9]*' --sort=-v:refname | head -n 1)
          
          # Fetch last pre-release
          last_pre_release_tag=$(git tag -l '[0-9]*.[0-9]*.[0-9]*-beta.*' --sort=-v:refname | head -n 1)
          
          if [ -z "$last_pre_release_tag" ] || [ "$last_release_tag" != "$last_tag" ]; then
            echo "Create new pre-release"
            IFS='.' read -r release_major release_minor release_patch <<< "$last_release_tag"
            incremented_release_patch_number=$((release_patch + 1))
            new_pre_release_tag="$release_major.$release_minor.$incremented_release_patch_number-beta.1"
          else
            echo "Last pre-release tag: $last_pre_release_tag"
            IFS='.' read -r prerelease_major prerelease_minor prerelease_patch prerelease_beta_number <<< "$last_pre_release_tag"
            incremented_beta_number=$((prerelease_beta_number + 1))
            new_pre_release_tag="$prerelease_major.$prerelease_minor.$prerelease_patch.$incremented_beta_number"
          fi
          
          echo "New pre-release tag: $new_pre_release_tag"
          echo "new_pre_release_tag=$new_pre_release_tag" >> $GITHUB_OUTPUT
          
      - name: Update manifest.json
        uses: jossef/action-set-json-field@v2.1
        with:
          file: custom_components/stellantis_vehicles/manifest.json
          field: version
          value: ${{ steps.pre-release-tag-name.outputs.new_pre_release_tag }}
          
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Update manifest.json ${{ steps.pre-release-tag-name.outputs.new_pre_release_tag }}"
          git tag ${{ steps.pre-release-tag-name.outputs.new_pre_release_tag }}
          
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.PAT }}
          tags: true
        
      - name: Create pre-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          tag_name: ${{ steps.pre-release-tag-name.outputs.new_pre_release_tag }}
          release_name: ${{ steps.pre-release-tag-name.outputs.new_pre_release_tag }}
          prerelease: true
