name: test-workflow.yml

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # serve per accedere a tutti i commit

    - name: Generate release notes
      id: generate_notes
      run: |
        # Ottieni hash e messaggio dei commit tra i due branch
        git log --no-merges --pretty=format:"%H %s (%an)" 2025.5.3..2025.5.4 | \
        # Escludi i revert
        grep -v "^.* Revert \"" | grep -v "^.* Update manifest.json version to" | grep -v '\.yaml' | grep -v '\.json' | grep -v '\.md' | \
        # Estrai gli hash dei commit revertati (li salviamo in una lista da escludere)
        while read -r line; do
            hash=$(echo "$line" | cut -d' ' -f1)
            msg=$(git log -1 --pretty=%s $hash)
            # Controlla se questo commit è stato revertato da qualcun altro
            if ! git log 2025.5.3..2025.5.4 --grep="$msg" --invert-grep --pretty=format:"%H" | grep -q $hash; then
                echo "- $(echo "$line" | cut -d' ' -f2-)"
            fi
        done
